<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_63f74571621f7',
	'title' => 'Page Settings',
	'fields' => array(
		array(
			'key' => 'field_63f756c10b13b',
			'label' => 'Hero',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 3,
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_63f35820b37ec',
			'label' => 'Hide header',
			'name' => 'hide_header',
			'type' => 'true_false',
			'instructions' => 'If selected YES then this field will hide the default header leaving the option to add your own element for the header.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 3,
			'message' => 'Select yes if you want to hide default header of this page and show something else',
			'default_value' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_63ee34902e937',
			'label' => 'Hero background image',
			'name' => 'hero_background_image',
			'type' => 'image',
			'instructions' => 'Minimum file size: 2000x760',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'uploader' => '',
			'return_format' => 'array',
			'acfe_thumbnail' => 0,
			'min_width' => 2000,
			'min_height' => 760,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '.jpeg, .jpg, .png, .webp, .svg',
			'preview_size' => 'medium',
			'library' => 'all',
		),
		array(
			'key' => 'field_63ee15c9c2ab5',
			'label' => 'Hero title',
			'name' => 'hero_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63ee336c2c8e1',
			'label' => 'Hero description',
			'name' => 'hero_description',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 3,
			'default_value' => '',
			'delay' => 0,
			'tabs' => 'visual',
			'toolbar' => 'full',
			'media_upload' => 0,
		),
		array(
			'key' => 'field_63f756d50b13c',
			'label' => 'Layout',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 3,
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_63f745c591bc9',
			'label' => 'Sidebar',
			'name' => 'has_sidebar',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 3,
			'message' => 'Selecting Yes will change page layout into a sidebar / content based.',
			'default_value' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_640b1a079e917',
			'label' => 'Excerpt',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 3,
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_640b1a179e918',
			'label' => 'Page excerpt',
			'name' => 'page_excerpt',
			'type' => 'wysiwyg',
			'instructions' => 'Used when post is in listing',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 3,
			'default_value' => '',
			'delay' => 0,
			'tabs' => 'visual',
			'toolbar' => 'basic',
			'media_upload' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfml_field_group_mode' => 'advanced',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1679491650,
));

endif;